version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: job_database
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password
    ports:
      - "3306:3306"

  parser:
    build:
      context: .
      dockerfile: Dockerfile.parser
    depends_on:
      - db

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    depends_on:
      - db
